### ISSUE TITLE
UIE的效果一般

### ISSUE THREAD

**Issue by yifan-chen-2020** [xusenlinzy/lit-ie#1]
uie的loss极小但是表现一般，是UIE的设置不对吗还是性能就这样？全部使用默认参数和提供的example data：
<img width="1554" alt="image" src="https://github.com/xusenlinzy/lit-ie/assets/71535401/af295061-202b-4cea-8cf2-a18e851d8fdf">

**Comment by xusenlinzy** [comment]
您好，UIE模型的优势是少样本和零样本抽取能力，项目中uie的数据是我随机选的一些，你可以试一试别的数据集，转换成相应的格式，看看效果怎么样。

![image](https://github.com/xusenlinzy/lit-ie/assets/111472355/21417d22-66d0-451b-8f16-00566c1f23cb)

一般来说，UIE模型主要是为了快速扩充训练数据，如上图所示
