### ISSUE TITLE
请教下efficient global pointer在超长矩阵下的效率问题

### ISSUE THREAD

**Issue by yifan-chen-2020** [xusenlinzy/lit-ie#2]
苏神，请教下，我现在需要处理的序列是4096长度的，在bert上接入了efficient global pointer结构，26分类，结果非常慢，debug看了下有两个问题：
1. 内存大小从20G->75G, 设置如下：
```
self.global_pointer = EfficientGlobalPointer(
    768,
    self.num_labels,
    64,
    use_rope=True
)
```
2. 因为内部代码结构的问题，实现的是稠密loss

请问如果换做sparse矩阵加速会很多吗？在超长序列下EGP是否有效率问题？

**Comment by xusenlinzy** [comment]
1. 您好，我不是苏神😅，根据[苏神博客](https://kexue.fm/archives/8888#%E5%AE%9E%E9%AA%8C%E7%BB%93%E6%9E%9C)里面说的是：相比于“multi hot”版的多标签交叉熵，使用稀疏版多标签交叉熵的模型在训练速度上能提高1.5倍而不会损失精度。

2. 本仓库支持稀疏版loss训练，请安装最新版本litie==0.2.5，训练示例见 [global_pointer_sparse.sh](https://github.com/xusenlinzy/lit-ie/blob/master/examples/named_entity_recognition/global_pointer_sparse.sh)，您可以测试一下效果

3. 如果您做的是实体抽取任务的话，我觉得可以将4096长度的句子按照语义切分成不超过512长度的若干短句子，基于这些短句子来训练EGP模型，推理的时候同样将长句子切分，最后将各个句子的抽取结果整合起来。
