### ISSUE TITLE
训练gplink，一直报错，调试texts一直为空，代码问题

### ISSUE THREAD

**Issue by xiaohuzi1996** [xusenlinzy/lit-ie#8]
![image](https://github.com/xusenlinzy/lit-ie/assets/55837663/66cbdf9a-dfe7-42f0-9876-3d2e9c7972ac)

texts,offset_mapping全为空，怎么解决啊

**Comment by xiaohuzi1996** [comment]
搞不懂为啥不放一个能跑通的代码，自己都没做个单元测试吧？

**Comment by xusenlinzy** [comment]
很久没有更新了，pytorch-lightning==2.0.5应该就可以了

**Comment by xiaohuzi1996** [comment]
> 很久没有更新了，pytorch-lightning==2.0.5应该就可以了

兄弟，你终于回复了，我试试吧

**Comment by xiaohuzi1996** [comment]
> > 很久没有更新了，pytorch-lightning==2.0.5应该就可以了
> 
> 兄弟，你终于回复了，我试试吧

/home/huzhang/anaconda3/envs/litie/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
Global seed set to 42
/home/huzhang/anaconda3/envs/litie/lib/python3.9/site-packages/litie/datasets/re/base.py:145: UserWarning: Labels has not been set, calling `setup('fit')`.
  rank_zero_warn("Labels has not been set, calling `setup('fit')`.")

卡着不动了呀。。是不是版本还不对？

**Comment by xusenlinzy** [comment]
![7ee651c3fc244274951f38b23cd3f08](https://github.com/xusenlinzy/lit-ie/assets/111472355/17bbe889-4039-4d76-acce-a443242d6323)
我这没问题

**Comment by xiaohuzi1996** [comment]
> ![7ee651c3fc244274951f38b23cd3f08](https://private-user-images.githubusercontent.com/111472355/316210401-17bbe889-4039-4d76-acce-a443242d6323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNjA5MDIsIm5iZiI6MTcxMTE2MDYwMiwicGF0aCI6Ii8xMTE0NzIzNTUvMzE2MjEwNDAxLTE3YmJlODg5LTQwMzktNGQ3Ni1hY2NlLWE0NDMyNDJkNjMyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwMjIzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjk2NjUyMGZhNGVjNzU2YWEzZjQxOTM4ZGZjYzcxNDcwMDk4MjRmOTNlOWQ0ZDJkZGVjYWNlN2ZjZDYwZjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2XY3YgQ6lA7uhS63DU_reBHDEfL1Yd8aQNxiJAda8aI) 我这没问题
> 
> 是不是你的模型权重没下载下来

export MODEL_NAME_OR_PATH=/disk/Eric/tools/Bert-Chinese-Text-Classification-Pytorch/chinese-roberta-wwm-ext
我的模型权重是指定的位置，你要不把你的跑通的requestments发我一份，我估计就是版本的问题

**Comment by xusenlinzy** [comment]
```
Package                   Version
------------------------- -----------
aiofiles                  23.2.1
aiohttp                   3.9.3
aiosignal                 1.3.1
altair                    5.2.0
annotated-types           0.6.0
anyio                     4.3.0
async-timeout             4.0.3
attrs                     23.2.0
blis                      0.7.11
catalogue                 2.0.10
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
cloudpathlib              0.16.0
colorama                  0.4.6
colorlog                  6.8.2
confection                0.1.4
contourpy                 1.2.0
cycler                    0.12.1
cymem                     2.0.8
datasets                  2.18.0
dill                      0.3.8
exceptiongroup            1.2.0
fastapi                   0.110.0
ffmpy                     0.3.2
filelock                  3.13.1
fonttools                 4.50.0
frozenlist                1.4.1
fsspec                    2024.2.0
gradio                    4.22.0
gradio_client             0.13.0
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
huggingface-hub           0.21.4
idna                      3.6
importlib_resources       6.4.0
jieba                     0.42.1
Jinja2                    3.1.3
joblib                    1.3.2
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
langcodes                 3.3.0
lightning-utilities       0.11.0
litie                     0.2.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.3
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.5
multiprocess              0.70.16
murmurhash                1.0.10
networkx                  3.2.1
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.4.99
nvidia-nvtx-cu12          12.1.105
orjson                    3.9.15
packaging                 24.0
pandas                    2.2.1
pillow                    10.2.0
pip                       24.0
preshed                   3.0.9
pyarrow                   15.0.2
pyarrow-hotfix            0.6
pydantic                  2.6.4
pydantic_core             2.16.3
pydub                     0.25.1
Pygments                  2.17.2
pyparsing                 3.1.2
pypinyin                  0.51.0
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytorch-lightning         2.0.5
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.34.0
regex                     2023.12.25
requests                  2.31.0
rich                      13.7.1
rpds-py                   0.18.0
ruff                      0.3.4
safetensors               0.4.2
scikit-learn              1.4.1.post1
scipy                     1.12.0
seaborn                   0.13.2
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                69.2.0
shellingham               1.5.4
six                       1.16.0
smart-open                6.4.0
sniffio                   1.3.1
spacy                     3.7.4
spacy-legacy              3.0.12
spacy-loggers             1.0.5
srsly                     2.4.8
starlette                 0.36.3
sympy                     1.12
thinc                     8.2.3
threadpoolctl             3.4.0
tokenizers                0.15.2
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.2.1
torchmetrics              0.11.4
tqdm                      4.66.2
transformers              4.39.1
triton                    2.2.0
typer                     0.9.0
typing_extensions         4.10.0
tzdata                    2024.1
urllib3                   2.2.1
uvicorn                   0.29.0
wasabi                    1.1.2
weasel                    0.3.4
websockets                11.0.3
wheel                     0.43.0
xxhash                    3.4.1
yarl                      1.9.4
zipp                      3.18.1

```

**Comment by xiaohuzi1996** [comment]
![image](https://github.com/xusenlinzy/lit-ie/assets/55837663/849fa654-feae-4ae1-a2b0-13cd4d608369)
还真的是环境的问题，我先跑试试看，多谢啦！

**Comment by xiaohuzi1996** [comment]
对了，duie的数据集，你这边有gplinker最佳的超参数配置吗？最佳的LOSS以及F1是多少呢？

**Comment by Chengyang852** [comment]
![image](https://github.com/xusenlinzy/lit-ie/assets/81755002/581ce074-fc83-47aa-a2e0-e7d4534c2618)
请问卡在这里不动了，是什么原因呢

**Comment by cuihangrui** [comment]
您好，我才用pip的安装方式进行训练，为什么训练结束后没有输出指标信息，而且也没有保存新的模型，是和我的xu训练epoch=1有关系吗?
![image](https://github.com/user-attachments/assets/41d2bf47-4cef-493a-b57e-4a5070c6e899)
![image](https://github.com/user-attachments/assets/1922cca7-b710-4891-b1e4-7747ba57ce8b)
@xiaohuzi1996 @Chengyang852 @xusenlinzy

**Comment by cuihangrui** [comment]
> 您好，我才用pip的安装方式进行训练，为什么训练结束后没有输出指标信息，而且也没有保存新的模型，是和我的xu训练epoch=1有关系吗？ ![图像](https://private-user-images.githubusercontent.com/86222753/359397760-41d2bf47-4cef-493a-b57e-4a5070c6e899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzkyNzgsIm5iZiI6MTcyNDgzODk3OCwicGF0aCI6Ii84NjIyMjc1My8zNTkzOTc3NjAtNDFkMmJmNDctNGNlZi00OTNhLWI1N2UtNGE1MDcwYzZlODk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA5NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OGRkYmNmOWNjNWZlNTg0NjI3ZDdlODVlMWQzZjJjNTIzNGQ5YTc1MzJlYzNmODU3NmRkOGY4YjkwNjM4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B2IgfnM-JY2GylI14CXsjiGN6Hz-fV_llmhi1mF0eKM) ![图像](https://private-user-images.githubusercontent.com/86222753/359397947-1922cca7-b710-4891-b1e4-7747ba57ce8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzkyNzgsIm5iZiI6MTcyNDgzODk3OCwicGF0aCI6Ii84NjIyMjc1My8zNTkzOTc5NDctMTkyMmNjYTctYjcxMC00ODkxLWIxZTQtNzc0N2JhNTdjZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA5NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OGNiYmQyOTc1MjI5NDMzOWQxZjVmYWI3ZjMwNmVmNDg4MzEzZDgxZjk0MWE4YjIyNWU4NGU4OWNkMDA1MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rd__TYsWSGk7OZYTApxPR1mHORyGdPElnvfZbWWZo3E)

问题以解决是参数设置的问题

**Comment by xusenlinzy** [comment]
本项目存在较多bug，一段时间后将移除，为了大家能够有更好的体验，请移步至https://github.com/xusenlinzy/FastIE
